[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npx next build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npx prisma db push && npx next start -p $PORT"
restartPolicyType = "on_failure"
